config/routes.rb
Rails.application.routes.draw do

  root 'hello#index'
  get 'hello/' => 'hello#about'

  devise_for :admins
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  resources :users  

  resources :dogs

  resources :searches

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/dog.rb
class Dog < ActiveRecord::Base

mount_uploader :avatar, AvatarUploader

end

# integer :id
    # string :name
    # integer :location
    # string :breed
    # string :age
    # string :gender
    # string :size
    # string :contact_email
    # string :avatar
    # datetime: created_at
    # datetime: updated_at

app/models/search.rb
class Search < ActiveRecord::Base

   def search_dogs
   
   dogs = Dog.all
   
   dogs = dogs.where("cast(location as text) like ?", "%#{location}%") if location.present?
   dogs = dogs.where("breed like ?", "%#{breed}%") if breed.present?
   dogs = dogs.where("age like ?", age) if age.present?
   dogs = dogs.where("gender like ?", gender) if gender.present?
   dogs = dogs.where("size like ?", size) if size.present?
   
   validates_presence_of :location

   return dogs

   end

   belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :searches
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!, :except => [:index, :about]

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:email, :password) }
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password) }
  end

  def after_sign_in_path_for(resource)
  	  new_search_path
  end

  def after_sign_up_path_for(resource)
      new_search_path
  end


end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  # GET /dogs
  # GET /dogs.json
  def index
    @dogs = Dog.all
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:avatar, :location, :name, :breed, :age, :gender, :size, :contact_email)
    end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end

  def about
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end

  def after_update_path_for(resource)
      new_search_path
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

	def new
	  @search = Search.new
	  @age = Dog.uniq.pluck(:age)
	  @gender = Dog.uniq.pluck(:gender)
	  @size = Dog.uniq.pluck(:size)
	end

	def create
	  @search = Search.create(search_params)
	  redirect_to @search
	end

	def show
	  @search = Search.find(params[:id])
	end

	def profile
	  @search = Search.find(params[:id])
	end

	private	

	def search_params
	   params.require(:search).permit(:location, :breed, :age, :gender, :size)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/dogs/_form.html.erb
<%= form_for(@dog) do |f| %>
  <% if @dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
      <% @dog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class ="row">

    <div class ="col-md-12">

      <div class="form-horizontal">
        <%= f.label "Upload a Photo" %><br>
        <%= f.file_field :avatar %><br><br>

        <%= f.label :remote_image_url, "or image URL" %><br />
        <%= f.text_field :remote_avatar_url %><br><br>

        <%= f.label :location %><br>
        <%= f.number_field :location, placeholder: "10001" %><br><br>

        <%= f.label :name %><br>
        <%= f.text_field :name %><br><br>

        <%= f.label :breed %><br>
        <%= f.text_field :breed %><br><br>

        <%= f.label :age %><br>
        <%= f.text_field :age %><br><br>

        <%= f.label :gender %><br>
        <%= f.text_field :gender %><br><br>

        <%= f.label :size %><br>
        <%= f.text_field :size %><br><br>

        <%= f.label :contact_email %><br>
        <%= f.text_field :contact_email %><br><br><br>

      </div>
      <div class="btn">
        <%= f.submit %>
      </div>

    </div>

  </div>
<% end %>

app/views/dogs/edit.html.erb
<h1>Editing Dog</h1>

<%= render 'form' %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/new.html.erb
<h1>New Dog</h1>

<%= render 'form' %>

<%= link_to 'Back', dogs_path %>

app/views/dogs/show.html.erb
<div class = "general-row" style="padding-bottom: 60px;">
<br><br><br>
<div class = "profile-container">
<%= image_tag @dog.avatar_url.to_s, :class => "profile-img"%>
</div>
<div class = "general-form">

<h2>Hi! My name is <%= @dog.name %>.</h2>
<h4>I'm a <%= @dog.size %>, <%= @dog.age %>, <%= @dog.gender %>, <%= @dog.breed %>. I'm temporarily living somewhere at <%= @dog.location %> but I'm looking for a forever home. If you want to come hang out with me, you can talk to my awesome caretakers below.</h4><br><h3>I can't wait to meet you!</h3>
<br><br>

<div class = "filler"></div>

<a target="_blank" href="<%= @dog.contact_email %>", class="btn btn-primary btn-md" style="color: #fff; padding: 15px; width: 25vw; margin-bottom: 20px;">Contact caretaker</a>


</div>
</div>

<%#= link_to 'Edit', edit_dog_path(@dog) %>
<%#= link_to 'Back', dogs_path %>

app/views/hello/about.html.erb
  <body>

    <div id = "section-1">

        <h1>Hello!</h1>

    </div>

    <div id = "section-2">

        <h2>Started in 2015 by <a target="_blank" href="http://e-l.li">Elli Park</a>, Found My Hound was built with the goal to find as many homes for pups in need.</h2>

        <h3>Currently, Found My Hound is in beta, and only serves a small population in New York. But I hope to expand to other parts of the country and to international grounds in the future.
        </h3>

    </div>

    <div id = "section-3">

        <h2>Thank you for visiting, hope you enjoyed! 😊</h2>

    </div>

  </body>

app/views/hello/index.html.erb
<!DOCTYPE html>
<html>
  <body>

  <header class = "header">
    <div class = "nav-container">
      <div class = "logo"><a href="/"><img src="https://dl.dropbox.com/s/jncnv2w0t7gvjtf/logo_2.png"></a></div> 
  
      <nav class = "header-nav">
        <% if user_signed_in? %>
        <p style="font-weight: 700;">Hello, <%= current_user.name %>!</p>
        <%= link_to 'Edit Profile', edit_user_registration_path%>
        <%= link_to 'New Search', new_search_path%>
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        <% else %>
        
        <%= link_to "About", hello_path %>
        <%= link_to "Login", new_user_session_path %>
        <% end %>
      </nav>

    </div>
  </header>

  <div class="content">
    <h2 id ="tagline">Find your perfect parter-in-crime.</h2>
    <h2 id="supportline">Found My Hound matches you with cute hounds in your area that need a home. Start your search today!</h2>

	    <div id="get_started">
        <% if user_signed_in? %>
        <%= link_to "Start a new search", new_search_path %>
        <% else %>
      	<%= link_to "Get started!", new_user_registration_path %>
        <% end %>

      </div>

  </div>
  <div id = "video_overlay"></div>
  <video autoplay muted poster="https://dl.dropbox.com/s/ib2ymrxh3xt23b7/test-background-vid-still.png" id="bgvid" loop>

      <source src="https://dl.dropbox.com/s/kmobgmh6lky722s/test-background-vid-short.webm" type="video/webm">

      <source src="https://dl.dropbox.com/s/ptiyyzbbiljlcid/test-background-vid-short.mp4" type="video/mp4">

  </video>

</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Found My Hound</title>

	 <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

	<!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

	<!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  
  <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <%= favicon_link_tag 'favicon.ico' %>

</head>

<body>

<div class = "container-fluid">
<% unless request.path == root_path %>
<header class = "user-header">

    <div class = "nav-container">
      <div class = "logo"><a href="/"><img src="https://dl.dropbox.com/s/jncnv2w0t7gvjtf/logo_2.png"></a></div> 
      
      <nav class = "user-header-nav">
        <% if user_signed_in? %>
        <p style="font-weight: 700;">Hello, <%= current_user.name %>! </p>
        <%= link_to 'Edit Profile', edit_user_registration_path%>
        <%= link_to 'New Search', new_search_path%>
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        <% else %>
        
        <%= link_to "About", hello_path %>
        <%= link_to "Login", new_user_session_path %>
        <% end %>
      </nav>

    </div>

</header>
<% end %>

<div class = "messages">

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>

<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

</div>

<%= yield %>

</div>
<% unless request.path == root_path %>
<footer class="footer">
<div class = "footer-container">
<p class="copyright">&copy; 2015 Found My Hound. All Rights Reserved.</p>
<p class="credit">Made with &#9829; by <a href="http://e-l.li" target="_blank">Elli</a> in NYC.</p>
</div>
</footer>
<% end %>


</body>
</html>

app/views/searches/new.html.erb
<div class = "general-row">
<div class = "search-form">
    <h2>What kind of hound are you looking for?</h2>
    <%= form_for @search, :html => {:class => "form-inline"} do |s|%>

        <%= s.label "I'm looking for a" %><br>

        <div class="form-group">
          <%= s.select :size, options_for_select(@size, selected = "Medium"), {:include_blank => "All"}, { :class => 'form-control' } %>
        </div>

      <div class="form-group">
          <%= s.select :age, options_for_select(@age, selected = "Young"), {:include_blank => "All"}, {:class => 'form-control'} %>
      </div>

      <div class="form-group">
          <%= s.select :gender, options_for_select(@gender, selected = "Female"), {:include_blank => "All"}, { :class => 'form-control' } %>

      </div>

      <div class="form-group">
        <%= s.text_field :breed, autofocus: true, placeholder: "Dachshund"%>
      </div>

      <br><br>

      <%= s.label "At" %><br>

      <div class="form-group">
        
        <%= s.text_field :location, autofocus: true, placeholder: "10001" %>
      </div>

      <br><br>
      
      <div class="actions"><%= s.submit "Search", :class => "btn btn-primary btn-md" %>
      </div>


    <% end %>

  </div>

</div>

app/views/searches/show.html.erb
<% if @search.search_dogs.empty? %>

	<div class = "general-row">
	<div class = "general-form show-form">
		<h2>Your Potential Hounds:</h2>

		<p class = "no-matches">We found no matches with your criteria... try searching again!</p>
		<%= button_to "Start a new search", new_search_path, method: :get, :class => "btn btn-primary btn-md" %>
	</div>
	</div>

<% else %>

	<h2 class = "search-h2">Your Potential Hounds:</h2>

	<% @search.search_dogs.in_groups_of(4, false).each do |c| %>

		<div class = "row results-row">

			<% c.each do |d| %>

			<div class="col-md-3">

				<%= link_to dog_path(d.id), :class => "img-responsive" do	%>
			  		<%= image_tag d.avatar_url.to_s %>
		  		<% end %>

		  	</div>

		  	<% end %>

	</div>

	<% end %>

	<div class="divider"></div>

<% end %>

app/views/users/show.html.erb
<h1><%= @user.searches.first.location %></h1>